#!/usr/bin/env php
<?php
// You probably need a package named something like 'php5-cli'
require_once('common.php');

if ($argc != 3 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
?>
This is a command-line driver for the boilerplate generator, as a test.

	Usage:
	<?php echo $argv[0]; ?> FileBaseName Extension
<?php
} else {
	require('support/sanitize.php');
	$ext = filter_var($argv[2], FILTER_SANITIZE_STRING);
	$filebase = filter_var($argv[1], FILTER_SANITIZE_STRING);

	require('generate.php');
	generateBoilerplate(array(
		'ext' => $ext,
		'filebase' => $filebase
		)
	);
}
?>
